matio-cpp: matioCpp::MatvarHandler::Ownership Class Reference
matioCpp::MatvarHandler::Ownership Class Reference
The Ownership class is used to define the ownership of a matvar.
#include <matioCpp/MatvarHandler.h>
Public Member Functions
Ownership (std::weak_ptr< PointerInfo > pointerToDeallocate)
Constructor.
~Ownership ()
Destructor.
bool isOwning (matvar_t *test)
Check if an input pointer is owned by this ownership object.
void own (matvar_t *owned, const MatvarHandler *owner, matioCpp::DeleteMode mode)
Add a pointer to the list of owned pointers.
void drop (matvar_t *previouslyOwned)
Drop a previously owned pointer and deleted if necessary.
void dropAll ()
Drops all the previously owned pointers and free those that need to be deallocated, including the main one.
Detailed Description
The Ownership class is used to define the ownership of a matvar.
SharedMatvar and WeakMatvar have a shared_ptr and a weak_ptr to it respectively.
Definition at line 109 of file MatvarHandler.h.
Constructor & Destructor Documentation
Ownership()
matioCpp::MatvarHandler::Ownership::Ownership (std::weak_ptr< PointerInfo > pointerToDeallocate)
Constructor.
Parameters
pointerToDeallocate A weak pointer toward the PointerInfo that contains the pointer to be freed.
Definition at line 110 of file MatvarHandler.cpp.
~Ownership()
matioCpp::MatvarHandler::Ownership::~Ownership ()
Destructor.
Definition at line 116 of file MatvarHandler.cpp.
Member Function Documentation
drop()
void matioCpp::MatvarHandler::Ownership::drop (matvar_t * previouslyOwned)
Drop a previously owned pointer and deleted if necessary.
Parameters
previouslyOwned The pointer that is not own anymore
Definition at line 146 of file MatvarHandler.cpp.
References std::unordered_map< K, T >::end(), std::unordered_map< K, T >::erase(), and std::unordered_map< K, T >::find().
dropAll()
void matioCpp::MatvarHandler::Ownership::dropAll ()
Drops all the previously owned pointers and free those that need to be deallocated, including the main one.
Definition at line 172 of file MatvarHandler.cpp.
References matioCpp::MatvarHandler::PointerInfo::DeletePointer().
isOwning()
bool matioCpp::MatvarHandler::Ownership::isOwning (matvar_t * test)
Check if an input pointer is owned by this ownership object.
Parameters
test The pointer to test
Returns
true if the ownership objects owns the pointer
Definition at line 121 of file MatvarHandler.cpp.
own()
void matioCpp::MatvarHandler::Ownership::own (matvar_t * owned, const MatvarHandler * owner, matioCpp::DeleteMode mode)
Add a pointer to the list of owned pointers.
This will not be deallocated as it is supposed to be part of the matvar_t pointer stored in m_ptr.
Parameters
owned The pointer to be considered owned.
owner The owner of owned. It is necessary to define the dependency tree.
mode Define how the owned variable has to be deleted
Definition at line 126 of file MatvarHandler.cpp.
References matioCpp::MatvarHandler::m_ptr, matioCpp::MatvarHandler::Dependency::mode, and matioCpp::MatvarHandler::Dependency::parent.
The documentation for this class was generated from the following files:
include/matioCpp/MatvarHandler.h
src/MatvarHandler.cpp