matio-cpp: matioCpp::File Class Reference
matioCpp::File Class Reference
#include <matioCpp/File.h>
Data Structures
class Impl
Public Member Functions
File ()
Default Constructor.
File (const std::string &name, matioCpp::FileMode mode=matioCpp::FileMode::ReadAndWrite)
Constructor opening the specified file.
File (const File &other)=delete
Deleted copy constructor, to avoid confusion on whether the content has been copied or not.
File (File &&other)
Move constructor.
~File ()
Destructor.
void operator= (const File &other)=delete
Deleted copy assignment, to avoid confusion on whether the content has been copied or not.
void operator= (File &&other)
Move assignement.
void close ()
Close the file.
bool open (const std::string &name, matioCpp::FileMode mode=matioCpp::FileMode::ReadAndWrite)
Open the specified file.
std::string name () const
The file name.
std::string header () const
The file header.
matioCpp::FileVersion version () const
The MAT file version.
matioCpp::FileMode mode () const
The mode with which the file has been opened.
std::vector< std::string > variableNames () const
Get the list of variables in the file.
matioCpp::Variable read (const std::string &name) const
Read a variable given the name.
bool write (const Variable &variable, matioCpp::Compression compression=matioCpp::Compression::None)
Write a Variable to a file.
template<class iterator >
bool write (iterator begin, iterator end, matioCpp::Compression compression=matioCpp::Compression::None)
Write a Variable to a file in a batch.
bool isOpen () const
Check if the file is open.
Static Public Member Functions
static File Create (const std::string &name, matioCpp::FileVersion version=matioCpp::FileVersion::Default, const std::string &header="")
Create a new file (static)
static bool Delete (const std::string &name)
Delete the specified file.
static bool Exists (const std::string &name)
Check if file exists and can be opened.
Detailed Description
Definition at line 15 of file File.h.
Constructor & Destructor Documentation
File() [1/4]
matioCpp::File::File ()
Default Constructor.
Definition at line 93 of file File.cpp.
File() [2/4]
matioCpp::File::File (const std::string & name, matioCpp::FileMode mode = matioCpp::FileMode::ReadAndWrite)
Constructor opening the specified file.
Parameters
name The name of the file to open.
mode The mode with which to open the file. By default, both reading and writing are allowed.
Note
If the mode is ReadAndWrite, a file with the same name is created if not found
Definition at line 99 of file File.cpp.
References mode(), name(), and open().
File() [3/4]
matioCpp::File::File (const File & other) delete
Deleted copy constructor, to avoid confusion on whether the content has been copied or not.
File() [4/4]
matioCpp::File::File (matioCpp::File && other)
Move constructor.
Parameters
other The other File from which the internal status has been taken.
Definition at line 105 of file File.cpp.
~File()
matioCpp::File::~File ()
Destructor.
Definition at line 110 of file File.cpp.
Member Function Documentation
close()
void matioCpp::File::close ()
Close the file.
Definition at line 120 of file File.cpp.
Create()
matioCpp::File matioCpp::File::Create (const std::string & name, matioCpp::FileVersion version = matioCpp::FileVersion::Default, const std::string & header = "") static
Create a new file (static)
This is the static version of open, with the addition that it is possible to have additional settings.
Parameters
name The name of the file to be openend.
version The MAT file version.
header This is an optional string that is added inside the MAT file. You can view the text in a MAT-file header using the cat command on the file on UNIX.
Returns
a newly created File object. The method isOpen() returnf false if something went wrong.
Definition at line 139 of file File.cpp.
References std::string::c_str(), std::endl(), std::string::find_last_of(), isOpen(), matioCpp::MAT4, matioCpp::MAT5, matioCpp::MAT7_3, matioCpp::ReadAndWrite, std::string::size(), std::string::substr(), std::to_string(), and matioCpp::Undefined.
Delete()
bool matioCpp::File::Delete (const std::string & name) static
Delete the specified file.
Parameters
name Name of the file to delete.
Returns
True if successful, false otherwise (for example, in Windows the file will not be deleted if open).
Definition at line 231 of file File.cpp.
References std::string::c_str(), and std::remove().
Exists()
bool matioCpp::File::Exists (const std::string & name) static
Check if file exists and can be opened.
Parameters
name The name of the file to check
Returns
True if the specified file exists, false otherwise
Definition at line 236 of file File.cpp.
References isOpen(), and matioCpp::ReadOnly.
header()
std::string matioCpp::File::header () const
The file header.
This is an optional string that is added inside the MAT file. You can view the text in a MAT-file header using the cat command on the file on UNIX.
Warning
This is available only if the matio version is >= 1.5.15
Returns
The file header
Definition at line 252 of file File.cpp.
References std::endl().
isOpen()
bool matioCpp::File::isOpen () const
Check if the file is open.
Returns
True if open.
Definition at line 409 of file File.cpp.
Referenced by Create(), and Exists().
mode()
matioCpp::FileMode matioCpp::File::mode () const
The mode with which the file has been opened.
Returns
The file mode. If the file is not open, it returns ReadOnly.
Definition at line 290 of file File.cpp.
Referenced by File(), and matioCpp::File::Impl::reset().
name()
std::string matioCpp::File::name () const
The file name.
Returns
The file name
Definition at line 242 of file File.cpp.
Referenced by File().
open()
bool matioCpp::File::open (const std::string & name, matioCpp::FileMode mode = matioCpp::FileMode::ReadAndWrite)
Open the specified file.
Parameters
name The name of the file to open.
mode The mode with which to open the file. By default, both reading and writing are allowed.
Returns
false in case of failure (the file does not exist, the file exist but cannot be written, ..)
Definition at line 125 of file File.cpp.
References std::string::c_str(), std::endl(), and matioCpp::ReadOnly.
Referenced by File().
operator=() [1/2]
void matioCpp::File::operator= (const File & other) delete
Deleted copy assignment, to avoid confusion on whether the content has been copied or not.
operator=() [2/2]
void matioCpp::File::operator= (matioCpp::File && other)
Move assignement.
Parameters
other The other File from which the internal status has been taken.
Definition at line 115 of file File.cpp.
References std::move().
read()
matioCpp::Variable matioCpp::File::read (const std::string & name) const
Read a variable given the name.
Parameters
name The name of the variable to be read
Returns
The desired Variable. The method isValid() would return false if something went wrong.
Note
Modifying the output variable will not change the file.
Definition at line 313 of file File.cpp.
References std::string::c_str(), std::endl(), matioCpp::Variable::isValid(), and matioCpp::MAT7_3.
variableNames()
std::vector< std::string > matioCpp::File::variableNames () const
Get the list of variables in the file.
Returns
The list of variables in the file.
Definition at line 295 of file File.cpp.
References std::vector< T >::resize().
version()
matioCpp::FileVersion matioCpp::File::version () const
The MAT file version.
Returns
The MAT file version
Definition at line 267 of file File.cpp.
References matioCpp::MAT4, matioCpp::MAT5, matioCpp::MAT7_3, and matioCpp::Undefined.
write() [1/2]
bool matioCpp::File::write (const Variable & variable, matioCpp::Compression compression = matioCpp::Compression::None)
Write a Variable to a file.
Parameters
variable The input variable.
compression The compression type to be used for writing the variable.
Note
The it performs a shallow copy of the variable.
Returns
True if successful.
Definition at line 341 of file File.cpp.
References matioCpp::Variable::dimensions(), matioCpp::DOUBLE, matioCpp::Element, std::endl(), matioCpp::SharedMatvar::get(), matioCpp::SharedMatvar::GetMatvarShallowDuplicate(), matioCpp::INT16, matioCpp::INT32, matioCpp::LOGICAL, matioCpp::MAT4, matioCpp::MultiDimensionalArray, matioCpp::ReadAndWrite, matioCpp::SINGLE, std::string::size(), matioCpp::Variable::toMatio(), matioCpp::UINT16, matioCpp::UINT8, matioCpp::Variable::valueType(), matioCpp::Variable::variableType(), matioCpp::Vector, and matioCpp::zlib.
write() [2/2]
template<class iterator > bool matioCpp::File::write (iterator begin, iterator end, matioCpp::Compression compression = matioCpp::Compression::None)
Write a Variable to a file in a batch.
Parameters
begin Iterator to the first element to be written
end Iterator to the first element that is not written
compression The compression type to be used for writing the variable.
Returns
True if successful.
Definition at line 24 of file File.tpp.
The documentation for this class was generated from the following files:
include/matioCpp/File.h
include/matioCpp/impl/File.tpp
src/File.cpp