matio-cpp: matioCpp::MatvarHandler Class Reference
matioCpp::MatvarHandler Class Reference abstract
#include <matioCpp/MatvarHandler.h>
Data Structures
struct Dependency
class Ownership
The Ownership class is used to define the ownership of a matvar.
class PointerInfo
Public Member Functions
MatvarHandler ()
Default constructor.
MatvarHandler (matvar_t *inputPtr, matioCpp::DeleteMode deleteMode=matioCpp::DeleteMode::Delete)
Constructor from an already existing matvar_t pointer.
MatvarHandler (const MatvarHandler &other)
Copy constructor.
MatvarHandler (MatvarHandler &&other)
Move constructor.
virtual ~MatvarHandler ()
Default destructor.
virtual matvar_t * get () const =0
Get the shared matvar_t pointer.
virtual bool isShared () const =0
Check if the onwership is shared with the current object.
virtual bool duplicateMatvar (const matvar_t *inputPtr)=0
Perform a deep copy of the input pointer.
virtual bool importMatvar (matvar_t *inputPtr)=0
Import the input pointer.
virtual MatvarHandler * pointerToDuplicate () const =0
Get a pointer to a duplicate of the MatvarHandler.
virtual WeakMatvar weakOwnership () const =0
Get a WeakMatvar version of the current MatvarHandler.
virtual void dropOwnedPointer (matvar_t *previouslyOwnedPointer)=0
Drop a pointer from the list of owned pointers.
ValueType valueType () const
Get the value type of the pointer.
VariableType variableType () const
Get the variable type of the pointer.
Static Public Member Functions
static matvar_t * GetMatvarDuplicate (const matvar_t *inputPtr)
Get a duplicate of the input matvar pointer/.
static void DeleteMatvar (matvar_t *pointerToDelete, DeleteMode mode=DeleteMode::Delete)
Delete the specified Matvar.
Protected Attributes
std::shared_ptr< PointerInfo > m_ptr
Shared pointer to a PointerInfo.
Detailed Description
Definition at line 13 of file MatvarHandler.h.
Constructor & Destructor Documentation
MatvarHandler() [1/4]
matioCpp::MatvarHandler::MatvarHandler ()
Default constructor.
Initializes matvar_t* to nullptr
Definition at line 188 of file MatvarHandler.cpp.
MatvarHandler() [2/4]
matioCpp::MatvarHandler::MatvarHandler (matvar_t * inputPtr, matioCpp::DeleteMode deleteMode = matioCpp::DeleteMode::Delete)
Constructor from an already existing matvar_t pointer.
Parameters
inputPtr The input matvar_t pointer
deleteMode The mode with which the pointer has to be deleted
Definition at line 193 of file MatvarHandler.cpp.
MatvarHandler() [3/4]
matioCpp::MatvarHandler::MatvarHandler (const MatvarHandler & other)
Copy constructor.
Parameters
other The other MatvarHandler to copy
Definition at line 199 of file MatvarHandler.cpp.
MatvarHandler() [4/4]
matioCpp::MatvarHandler::MatvarHandler (matioCpp::MatvarHandler && other)
Move constructor.
Parameters
other The other MatvarHandler to move
Definition at line 205 of file MatvarHandler.cpp.
~MatvarHandler()
virtual matioCpp::MatvarHandler::~MatvarHandler () inline virtual
Default destructor.
Definition at line 200 of file MatvarHandler.h.
Member Function Documentation
DeleteMatvar()
void matioCpp::MatvarHandler::DeleteMatvar (matvar_t * pointerToDelete, DeleteMode mode = DeleteMode::Delete) static
Delete the specified Matvar.
Parameters
pointerToDelete The matvar to be deleted
mode The deletion mode
Definition at line 303 of file MatvarHandler.cpp.
Referenced by matioCpp::Variable::initializeComplexVariable(), matioCpp::Variable::initializeVariable(), matioCpp::Variable::setCellElement(), and matioCpp::Variable::setStructField().
dropOwnedPointer()
virtual void matioCpp::MatvarHandler::dropOwnedPointer (matvar_t * previouslyOwnedPointer) pure virtual
Drop a pointer from the list of owned pointers.
Parameters
previouslyOwnedPointer The pointer that is not owned anymore
Implemented in matioCpp::WeakMatvar, and matioCpp::SharedMatvar.
duplicateMatvar()
virtual bool matioCpp::MatvarHandler::duplicateMatvar (const matvar_t * inputPtr) pure virtual
Perform a deep copy of the input pointer.
Parameters
inputPtr The input pointer
Returns
True if successful, false otherwise (e.g. if isShared is false, or the input pointer is null).
Implemented in matioCpp::SharedMatvar, and matioCpp::WeakMatvar.
Referenced by matioCpp::Variable::Variable().
get()
virtual matvar_t* matioCpp::MatvarHandler::get () const pure virtual
Get the shared matvar_t pointer.
Returns
the shared matvar_t pointer. It may be null if matvar_t has never been allocated.
Implemented in matioCpp::WeakMatvar, and matioCpp::SharedMatvar.
Referenced by matioCpp::CellArray::CellArray(), matioCpp::Element< T >::Element(), matioCpp::Variable::initializeVariable(), matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray(), matioCpp::Struct::Struct(), matioCpp::StructArray::StructArray(), and matioCpp::Vector< T >::Vector().
GetMatvarDuplicate()
matvar_t * matioCpp::MatvarHandler::GetMatvarDuplicate (const matvar_t * inputPtr) static
Get a duplicate of the input matvar pointer/.
Parameters
inputPtr The input pointer
Returns
A copy of the pointer
Definition at line 221 of file MatvarHandler.cpp.
References matioCpp::CellArray, std::vector< T >::data(), std::endl(), matioCpp::SharedMatvar::get(), matioCpp::get_types_from_matvart(), matioCpp::SharedMatvar::GetMatvarShallowDuplicate(), matioCpp::Struct, and matioCpp::StructArray.
Referenced by matioCpp::CellArray::CellArray(), matioCpp::SharedMatvar::duplicateMatvar(), matioCpp::StructArray::fromVectorOfStructs(), matioCpp::CellArray::fromVectorOfVariables(), matioCpp::Struct::fromVectorOfVariables(), matioCpp::Variable::setCellElement(), matioCpp::Variable::setStructField(), matioCpp::Struct::Struct(), and matioCpp::StructArray::StructArray().
importMatvar()
virtual bool matioCpp::MatvarHandler::importMatvar (matvar_t * inputPtr) pure virtual
Import the input pointer.
Parameters
inputPtr The input pointer
Returns
True if successful, false otherwise (e.g. if isShared is false, or the input pointer is null).
Implemented in matioCpp::SharedMatvar, and matioCpp::WeakMatvar.
Referenced by matioCpp::Variable::initializeVariable().
isShared()
virtual bool matioCpp::MatvarHandler::isShared () const pure virtual
Check if the onwership is shared with the current object.
Returns
True if the current object is sharing the ownership of the matvar_t.
Implemented in matioCpp::WeakMatvar, and matioCpp::SharedMatvar.
pointerToDuplicate()
virtual MatvarHandler* matioCpp::MatvarHandler::pointerToDuplicate () const pure virtual
Get a pointer to a duplicate of the MatvarHandler.
The pointed object has to be deallocated manually
Returns
A pointer to a copy of the MatvarHandler.
Implemented in matioCpp::WeakMatvar, and matioCpp::SharedMatvar.
valueType()
matioCpp::ValueType matioCpp::MatvarHandler::valueType () const
Get the value type of the pointer.
Returns
The value type of the pointer
Definition at line 211 of file MatvarHandler.cpp.
Referenced by matioCpp::CellArray::CellArray(), matioCpp::Element< T >::Element(), matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray(), matioCpp::Struct::Struct(), matioCpp::StructArray::StructArray(), and matioCpp::Vector< T >::Vector().
variableType()
matioCpp::VariableType matioCpp::MatvarHandler::variableType () const
Get the variable type of the pointer.
Returns
The variable type of the pointer
Definition at line 216 of file MatvarHandler.cpp.
Referenced by matioCpp::CellArray::CellArray(), matioCpp::Element< T >::Element(), matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray(), matioCpp::Struct::Struct(), matioCpp::StructArray::StructArray(), and matioCpp::Vector< T >::Vector().
weakOwnership()
virtual WeakMatvar matioCpp::MatvarHandler::weakOwnership () const pure virtual
Get a WeakMatvar version of the current MatvarHandler.
Returns
A WeakMatvar version of the current MatvarHandler.
Implemented in matioCpp::WeakMatvar, and matioCpp::SharedMatvar.
Referenced by matioCpp::WeakMatvar::WeakMatvar().
Field Documentation
m_ptr
std::shared_ptr<PointerInfo> matioCpp::MatvarHandler::m_ptr protected
Shared pointer to a PointerInfo.
This allows sharing the same matvar_t across several objects.
Since it is separate from the ownership, it is possible to avoid deallocating this pointer if necessary (e.g. when getting an element from a struct).
Definition at line 167 of file MatvarHandler.h.
Referenced by matioCpp::MatvarHandler::PointerInfo::changePointer(), matioCpp::MatvarHandler::PointerInfo::deletePointer(), matioCpp::SharedMatvar::GetMatvarShallowDuplicate(), matioCpp::MatvarHandler::PointerInfo::operator!=(), matioCpp::SharedMatvar::operator=(), matioCpp::WeakMatvar::operator=(), matioCpp::MatvarHandler::Ownership::own(), matioCpp::MatvarHandler::PointerInfo::pointer(), matioCpp::WeakMatvar::WeakMatvar(), and matioCpp::SharedMatvar::weakOwnership().
The documentation for this class was generated from the following files:
include/matioCpp/MatvarHandler.h
src/MatvarHandler.cpp