matio-cpp: matioCpp::File::Impl Class Reference
matioCpp::File::Impl Class Reference
Public Member Functions
void close ()
void freePtr ()
void reset (mat_t *newPtr, matioCpp::FileMode mode)
Impl ()
~Impl ()
std::string isVariableValid (const matioCpp::Variable &input)
Data Fields
mat_t * mat_ptr {nullptr}
matioCpp::FileMode fileMode {matioCpp::FileMode::ReadOnly}
Detailed Description
Definition at line 16 of file File.cpp.
Constructor & Destructor Documentation
Impl()
matioCpp::File::Impl::Impl () inline
Definition at line 49 of file File.cpp.
~Impl()
matioCpp::File::Impl::~Impl () inline
Definition at line 52 of file File.cpp.
References close().
Member Function Documentation
close()
void matioCpp::File::Impl::close () inline
Definition at line 22 of file File.cpp.
References fileMode, freePtr(), and matioCpp::ReadOnly.
Referenced by ~Impl().
freePtr()
void matioCpp::File::Impl::freePtr () inline
Definition at line 28 of file File.cpp.
References mat_ptr.
Referenced by close(), and reset().
isVariableValid()
std::string matioCpp::File::Impl::isVariableValid (const matioCpp::Variable & input) inline
Definition at line 57 of file File.cpp.
References matioCpp::Variable::isValid(), matioCpp::Variable::name(), and std::string::size().
reset()
void matioCpp::File::Impl::reset (mat_t * newPtr, matioCpp::FileMode mode) inline
Definition at line 37 of file File.cpp.
References fileMode, freePtr(), mat_ptr, matioCpp::File::mode(), and matioCpp::ReadOnly.
Field Documentation
fileMode
matioCpp::FileMode matioCpp::File::Impl::fileMode {matioCpp::FileMode::ReadOnly}
Definition at line 20 of file File.cpp.
Referenced by close(), and reset().
mat_ptr
mat_t* matioCpp::File::Impl::mat_ptr {nullptr}
Definition at line 19 of file File.cpp.
Referenced by freePtr(), and reset().
The documentation for this class was generated from the following file:
src/File.cpp