matio-cpp: matioCpp::Element< T > Class Template Reference
matioCpp::Element< T > Class Template Reference
Element allows having a 1x1 variable (like double, int,..) castable to a primitive type.
#include <matioCpp/Element.h>
Public Types
using type = T
using element_type = typename get_type< T >::type
Defines the type specified in the template.
using value_type = std::remove_cv_t< element_type >
Defines the type of the Element.
using reference = element_type &
Defines the type of the Element.
using pointer = typename std::allocator_traits< std::allocator< element_type > >::pointer
The reference type.
using const_pointer = typename std::allocator_traits< std::allocator< element_type > >::const_pointer
The pointer type.
Public Member Functions
Element ()
The const pointer type.
Element (const std::string &name)
Constructor.
Element (const std::string &name, element_type inputValue)
Constructor.
Element (const Element< T > &other)
Copy constructor.
Element (Element< T > &&other)
Move constructor.
Element (const MatvarHandler &handler)
Constructor to share the data ownership of another variable.
~Element ()
Destructor.
Element< T > & operator= (const Element< T > &other)
Assignement operator (copy) from another Element.
Element< T > & operator= (Element< T > &&other)
Assignement operator (move) from another Element.
Element< T > & operator= (element_type value)
Assignement operator (copy) from an element of type T.
matioCpp::Span< element_type > toSpan ()
Get this Vector as a Span.
const matioCpp::Span< const element_type > toSpan () const
Get this Vector as a Span (const version)
bool setName (const std::string &newName)
Change the name of the Variable.
reference operator() ()
Access the Element.
value_type operator() () const
Access the Element.
operator element_type () const
Casting operator to T.
Public Member Functions inherited from matioCpp::Variable
Variable ()
Default constructor.
Variable (const matvar_t *inputVar)
Constructor from an existing matvar_t pointer.
Variable (const Variable &other)
Copy constructor.
Variable (Variable &&other)
Move constructor.
Variable (const MatvarHandler &handler)
Constructor to share the data ownership of another variable.
~Variable ()
Destructor.
Variable & operator= (const Variable &other)
Copy assignement.
Variable & operator= (Variable &&other)
Move assignement.
bool fromMatio (const matvar_t *inputVar)
Set this variable from an existing matio variable.
bool fromOther (const Variable &other)
Set this variable from another variable.
bool fromOther (Variable &&other)
Set this variable from another variable.
const matvar_t * toMatio () const
Convert this Variable to a matio variable.
matvar_t * toMatio ()
Convert this Variable to a matio variable.
std::string name () const
Get the name of the Variable.
matioCpp::VariableType variableType () const
Get the VariableType.
matioCpp::ValueType valueType () const
Get the ValueType.
bool isComplex () const
Get if the variable is complex.
matioCpp::Span< const size_t > dimensions () const
Get the dimensions of this object.
bool isValid () const
Check if the variable is valid.
matioCpp::Variable operator[] (const std::string &el)
Access field with specific name.
const matioCpp::Variable operator[] (const std::string &el) const
Access field with specific name.
template<typename T >
matioCpp::Element< T > asElement ()
Cast the variable as a Element.
template<typename T >
const matioCpp::Element< T > asElement () const
Cast the variable as a const Element.
template<typename T >
matioCpp::Vector< T > asVector ()
Cast the variable as a Vector.
template<typename T >
const matioCpp::Vector< T > asVector () const
Cast the variable as a const Vector.
matioCpp::String asString ()
Cast the variable as a String.
const matioCpp::String asString () const
Cast the variable as a const String.
matioCpp::String16 asString16 ()
Cast the variable as a String16.
const matioCpp::String16 asString16 () const
Cast the variable as a const String16.
matioCpp::String32 asString32 ()
Cast the variable as a String32.
const matioCpp::String32 asString32 () const
Cast the variable as a const String32.
template<typename T >
matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray ()
Cast the variable as a MultiDimensionalArray.
template<typename T >
const matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray () const
Cast the variable as a const MultiDimensionalArray.
matioCpp::CellArray asCellArray ()
Cast the variable as a CellArray.
const matioCpp::CellArray asCellArray () const
Cast the variable as a const CellArray.
matioCpp::Struct asStruct ()
Cast the variable as a Struct.
const matioCpp::Struct asStruct () const
Cast the variable as a const Struct.
matioCpp::StructArray asStructArray ()
Cast the variable as a StructArray.
const matioCpp::StructArray asStructArray () const
Cast the variable as a const StructArray.
Additional Inherited Members
Protected Member Functions inherited from matioCpp::Variable
bool initializeVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *data)
Initialize the variable.
bool initializeComplexVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *realData, void *imaginaryData)
Initialize a complex variable.
template<typename T >
bool initializeComplexVector (const std::string &name, const Span< T > realInputVector, const Span< T > imaginaryInputVector)
Initialize a complex vector.
bool changeName (const std::string &newName)
Change the name of the variable.
size_t getArrayNumberOfElements () const
Get the total number of elements in the array.
bool setCellElement (size_t linearIndex, const Variable &newValue)
Set a cell element at a specified linear position.
Variable getCellElement (size_t linearIndex)
Get a cell element at a specified linear position.
const Variable getCellElement (size_t linearIndex) const
Get a cell element at a specified linear position.
size_t getStructNumberOfFields () const
Get the total number of fields in the variable, considered as a struct.
char *const * getStructFields () const
Get the list of fields in the variable, considered as a struct.
bool getStructFieldIndex (const std::string &field, size_t &index) const
Get the index of the specified field in the variable, considered as a struct.
bool setStructField (size_t index, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct at the specified position.
bool addStructField (const std::string &newField)
Add a new field to the variable, considered as a struct.
bool setStructField (const std::string &field, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct given the newValue name.
Variable getStructField (size_t index, size_t structPositionInArray=0)
Get the specified field in the variable, considered as a struct.
const Variable getStructField (size_t index, size_t structPositionInArray=0) const
Get the specified field in the variable, considered as a struct.
Struct getStructArrayElement (size_t linearIndex)
Get an element of the variable, considered as a StructArray.
const Struct getStructArrayElement (size_t linearIndex) const
Get an element of the variable, considered as a StructArray.
Detailed Description
template<typename T>
class matioCpp::Element< T >
Element allows having a 1x1 variable (like double, int,..) castable to a primitive type.
Definition at line 19 of file Element.h.
Member Typedef Documentation
const_pointer
template<typename T > using matioCpp::Element< T >::const_pointer = typename std::allocator_traits<std::allocator<element_type> >::const_pointer
The pointer type.
Definition at line 43 of file Element.h.
element_type
template<typename T > using matioCpp::Element< T >::element_type = typename get_type<T>::type
Defines the type specified in the template.
Definition at line 35 of file Element.h.
pointer
template<typename T > using matioCpp::Element< T >::pointer = typename std::allocator_traits<std::allocator<element_type> >::pointer
The reference type.
Definition at line 41 of file Element.h.
reference
template<typename T > using matioCpp::Element< T >::reference = element_type&
Defines the type of the Element.
without "const".
Definition at line 39 of file Element.h.
type
template<typename T > using matioCpp::Element< T >::type = T
Definition at line 33 of file Element.h.
value_type
template<typename T > using matioCpp::Element< T >::value_type = std::remove_cv_t<element_type>
Defines the type of the Element.
Definition at line 37 of file Element.h.
Constructor & Destructor Documentation
Element() [1/6]
template<typename T > matioCpp::Element< T >::Element
The const pointer type.
Default Constructor
Note
The name is set to "unnamed_element".
Definition at line 44 of file Element.tpp.
Element() [2/6]
template<typename T > matioCpp::Element< T >::Element (const std::string & name)
Constructor.
Parameters
name The name of the Element
Definition at line 61 of file Element.tpp.
Element() [3/6]
template<typename T > matioCpp::Element< T >::Element (const std::string & name, element_type inputValue)
Constructor.
Parameters
name The name of the Element
inputValue The value to be given to the element
Element() [4/6]
template<typename T > matioCpp::Element< T >::Element (const Element< T > & other)
Copy constructor.
Definition at line 85 of file Element.tpp.
Element() [5/6]
template<typename T > matioCpp::Element< T >::Element (Element< T > && other)
Move constructor.
Definition at line 91 of file Element.tpp.
References std::forward().
Element() [6/6]
template<typename T > matioCpp::Element< T >::Element (const MatvarHandler & handler)
Constructor to share the data ownership of another variable.
Parameters
handler The MatvarHandler handler to the matvar_t which has to be shared.
Definition at line 97 of file Element.tpp.
References matioCpp::Element, matioCpp::MatvarHandler::get(), matioCpp::Variable::initializeVariable(), matioCpp::MatvarHandler::valueType(), and matioCpp::MatvarHandler::variableType().
~Element()
template<typename T > matioCpp::Element< T >::~Element
Destructor.
Definition at line 113 of file Element.tpp.
Member Function Documentation
operator element_type()
template<typename T > matioCpp::Element< T >::operator element_type () const
Casting operator to T.
operator()() [1/2]
template<typename T > matioCpp::Element< T >::reference matioCpp::Element< T >::operator()
Access the Element.
Returns
A reference to the element.
Definition at line 158 of file Element.tpp.
operator()() [2/2]
template<typename T > matioCpp::Element< T >::value_type matioCpp::Element< T >::operator()
Access the Element.
Returns
A copy to the element.
Definition at line 164 of file Element.tpp.
operator=() [1/3]
template<typename T > matioCpp::Element< T > & matioCpp::Element< T >::operator= (const Element< T > & other)
Assignement operator (copy) from another Element.
Parameters
other The other Element.
Note
Also the name is copied
Returns
A reference to this Element.
Definition at line 119 of file Element.tpp.
operator=() [2/3]
template<typename T > matioCpp::Element< T > & matioCpp::Element< T >::operator= (Element< T > && other)
Assignement operator (move) from another Element.
Parameters
other The other Element.
Note
Also the name is copied
Returns
A reference to this Element.
Definition at line 126 of file Element.tpp.
References std::forward().
operator=() [3/3]
template<typename T > Element<T>& matioCpp::Element< T >::operator= (element_type value)
Assignement operator (copy) from an element of type T.
Parameters
value The element to copy.
Returns
A reference to this Element.
setName()
template<typename T > bool matioCpp::Element< T >::setName (const std::string & newName)
Change the name of the Variable.
Parameters
newName The new name
Returns
True if successful.
Definition at line 152 of file Element.tpp.
toSpan() [1/2]
template<typename T > matioCpp::Span< typename matioCpp::Element< T >::element_type > matioCpp::Element< T >::toSpan
Get this Vector as a Span.
Definition at line 140 of file Element.tpp.
References matioCpp::make_span().
toSpan() [2/2]
template<typename T > const matioCpp::Span< const typename matioCpp::Element< T >::element_type > matioCpp::Element< T >::toSpan
Get this Vector as a Span (const version)
Definition at line 146 of file Element.tpp.
References matioCpp::make_span().
The documentation for this class was generated from the following files:
include/matioCpp/Element.h
include/matioCpp/impl/Element.tpp