matio-cpp: matioCpp::MultiDimensionalArray< T > Class Template Reference
matioCpp::MultiDimensionalArray< T > Class Template Reference
MultiDimensionalArray is a particular type of Variable specialized for multidimensional arrays of a generic type T.
#include <matioCpp/MultiDimensionalArray.h>
Public Types
using type = T
using element_type = typename get_type< T >::type
Defines the type specified in the template.
using value_type = std::remove_cv_t< element_type >
Defines the type of an element of the MultiDimensionalArray.
using allocator_type = std::allocator< element_type >
Defines the type of an element of the MultiDimensionalArray without "const".
using index_type = size_t
Defines how to allocate T.
using reference = element_type &
The type used for indices.
using pointer = typename std::allocator_traits< std::allocator< element_type > >::pointer
The reference type.
using const_pointer = typename std::allocator_traits< std::allocator< element_type > >::const_pointer
The pointer type.
Public Member Functions
MultiDimensionalArray ()
The const pointer type.
MultiDimensionalArray (const std::string &name)
Constructor.
MultiDimensionalArray (const std::string &name, const std::vector< index_type > &dimensions)
Constructor.
MultiDimensionalArray (const std::string &name, const std::vector< index_type > &dimensions, const_pointer inputVector)
Constructor.
MultiDimensionalArray (const MultiDimensionalArray< T > &other)
Copy constructor.
MultiDimensionalArray (MultiDimensionalArray< T > &&other)
Move constructor.
MultiDimensionalArray (const MatvarHandler &handler)
Constructor to share the data ownership of another variable.
~MultiDimensionalArray ()
Destructor.
MultiDimensionalArray< T > & operator= (const MultiDimensionalArray< T > &other)
Assignement operator (copy) from another MultiDimensionalArray.
MultiDimensionalArray< T > & operator= (MultiDimensionalArray< T > &&other)
Assignement operator (move) from another MultiDimensionalArray.
bool fromVectorizedArray (const std::vector< index_type > &dimensions, const_pointer inputVector)
Set from a vectorized array.
index_type rawIndexFromIndices (const std::vector< index_type > &el) const
Get the index in the vectorized array corresponding to the provided indices.
bool indicesFromRawIndex (size_t rawIndex, std::vector< index_type > &el) const
Get the indices given the raw index.
matioCpp::Span< element_type > toSpan ()
Get this MultiDimensionalArray as a Span.
const matioCpp::Span< const element_type > toSpan () const
Get this MultiDimensionalArray as a Span (const version)
bool setName (const std::string &newName)
Change the name of the Variable.
void resize (const std::vector< index_type > &newDimensions)
Resize the vector.
void clear ()
Clear the multidimensional array.
pointer data ()
Direct access to the underlying array.
const_pointer data () const
Direct access to the underlying array.
index_type numberOfElements () const
Get the total number of elements in the array.
reference operator() (const std::vector< index_type > &el)
Access specified element.
value_type operator() (const std::vector< index_type > &el) const
Access specified element.
reference operator() (index_type el)
Access specified element.
value_type operator() (index_type el) const
Access specified element.
reference operator[] (const std::vector< index_type > &el)
Access specified element.
value_type operator[] (const std::vector< index_type > &el) const
Access specified element.
reference operator[] (index_type el)
Access specified element.
value_type operator[] (index_type el) const
Access specified element.
Public Member Functions inherited from matioCpp::Variable
Variable ()
Default constructor.
Variable (const matvar_t *inputVar)
Constructor from an existing matvar_t pointer.
Variable (const Variable &other)
Copy constructor.
Variable (Variable &&other)
Move constructor.
Variable (const MatvarHandler &handler)
Constructor to share the data ownership of another variable.
~Variable ()
Destructor.
Variable & operator= (const Variable &other)
Copy assignement.
Variable & operator= (Variable &&other)
Move assignement.
bool fromMatio (const matvar_t *inputVar)
Set this variable from an existing matio variable.
bool fromOther (const Variable &other)
Set this variable from another variable.
bool fromOther (Variable &&other)
Set this variable from another variable.
const matvar_t * toMatio () const
Convert this Variable to a matio variable.
matvar_t * toMatio ()
Convert this Variable to a matio variable.
std::string name () const
Get the name of the Variable.
matioCpp::VariableType variableType () const
Get the VariableType.
matioCpp::ValueType valueType () const
Get the ValueType.
bool isComplex () const
Get if the variable is complex.
matioCpp::Span< const size_t > dimensions () const
Get the dimensions of this object.
bool isValid () const
Check if the variable is valid.
matioCpp::Variable operator[] (const std::string &el)
Access field with specific name.
const matioCpp::Variable operator[] (const std::string &el) const
Access field with specific name.
template<typename T >
matioCpp::Element< T > asElement ()
Cast the variable as a Element.
template<typename T >
const matioCpp::Element< T > asElement () const
Cast the variable as a const Element.
template<typename T >
matioCpp::Vector< T > asVector ()
Cast the variable as a Vector.
template<typename T >
const matioCpp::Vector< T > asVector () const
Cast the variable as a const Vector.
matioCpp::String asString ()
Cast the variable as a String.
const matioCpp::String asString () const
Cast the variable as a const String.
matioCpp::String16 asString16 ()
Cast the variable as a String16.
const matioCpp::String16 asString16 () const
Cast the variable as a const String16.
matioCpp::String32 asString32 ()
Cast the variable as a String32.
const matioCpp::String32 asString32 () const
Cast the variable as a const String32.
template<typename T >
matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray ()
Cast the variable as a MultiDimensionalArray.
template<typename T >
const matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray () const
Cast the variable as a const MultiDimensionalArray.
matioCpp::CellArray asCellArray ()
Cast the variable as a CellArray.
const matioCpp::CellArray asCellArray () const
Cast the variable as a const CellArray.
matioCpp::Struct asStruct ()
Cast the variable as a Struct.
const matioCpp::Struct asStruct () const
Cast the variable as a const Struct.
matioCpp::StructArray asStructArray ()
Cast the variable as a StructArray.
const matioCpp::StructArray asStructArray () const
Cast the variable as a const StructArray.
Additional Inherited Members
Protected Member Functions inherited from matioCpp::Variable
bool initializeVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *data)
Initialize the variable.
bool initializeComplexVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *realData, void *imaginaryData)
Initialize a complex variable.
template<typename T >
bool initializeComplexVector (const std::string &name, const Span< T > realInputVector, const Span< T > imaginaryInputVector)
Initialize a complex vector.
bool changeName (const std::string &newName)
Change the name of the variable.
size_t getArrayNumberOfElements () const
Get the total number of elements in the array.
bool setCellElement (size_t linearIndex, const Variable &newValue)
Set a cell element at a specified linear position.
Variable getCellElement (size_t linearIndex)
Get a cell element at a specified linear position.
const Variable getCellElement (size_t linearIndex) const
Get a cell element at a specified linear position.
size_t getStructNumberOfFields () const
Get the total number of fields in the variable, considered as a struct.
char *const * getStructFields () const
Get the list of fields in the variable, considered as a struct.
bool getStructFieldIndex (const std::string &field, size_t &index) const
Get the index of the specified field in the variable, considered as a struct.
bool setStructField (size_t index, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct at the specified position.
bool addStructField (const std::string &newField)
Add a new field to the variable, considered as a struct.
bool setStructField (const std::string &field, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct given the newValue name.
Variable getStructField (size_t index, size_t structPositionInArray=0)
Get the specified field in the variable, considered as a struct.
const Variable getStructField (size_t index, size_t structPositionInArray=0) const
Get the specified field in the variable, considered as a struct.
Struct getStructArrayElement (size_t linearIndex)
Get an element of the variable, considered as a StructArray.
const Struct getStructArrayElement (size_t linearIndex) const
Get an element of the variable, considered as a StructArray.
Detailed Description
template<typename T>
class matioCpp::MultiDimensionalArray< T >
MultiDimensionalArray is a particular type of Variable specialized for multidimensional arrays of a generic type T.
Note
The underlying array is in column-major format.
Definition at line 21 of file MultiDimensionalArray.h.
Member Typedef Documentation
allocator_type
template<typename T > using matioCpp::MultiDimensionalArray< T >::allocator_type = std::allocator<element_type>
Defines the type of an element of the MultiDimensionalArray without "const".
Useful to use make_span.
Definition at line 41 of file MultiDimensionalArray.h.
const_pointer
template<typename T > using matioCpp::MultiDimensionalArray< T >::const_pointer = typename std::allocator_traits<std::allocator<element_type> >::const_pointer
The pointer type.
Definition at line 49 of file MultiDimensionalArray.h.
element_type
template<typename T > using matioCpp::MultiDimensionalArray< T >::element_type = typename get_type<T>::type
Defines the type specified in the template.
Definition at line 37 of file MultiDimensionalArray.h.
index_type
template<typename T > using matioCpp::MultiDimensionalArray< T >::index_type = size_t
Defines how to allocate T.
Definition at line 43 of file MultiDimensionalArray.h.
pointer
template<typename T > using matioCpp::MultiDimensionalArray< T >::pointer = typename std::allocator_traits<std::allocator<element_type> >::pointer
The reference type.
Definition at line 47 of file MultiDimensionalArray.h.
reference
template<typename T > using matioCpp::MultiDimensionalArray< T >::reference = element_type&
The type used for indices.
Definition at line 45 of file MultiDimensionalArray.h.
type
template<typename T > using matioCpp::MultiDimensionalArray< T >::type = T
Definition at line 35 of file MultiDimensionalArray.h.
value_type
template<typename T > using matioCpp::MultiDimensionalArray< T >::value_type = std::remove_cv_t<element_type>
Defines the type of an element of the MultiDimensionalArray.
Definition at line 39 of file MultiDimensionalArray.h.
Constructor & Destructor Documentation
MultiDimensionalArray() [1/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray
The const pointer type.
Default Constructor
Note
The name is set to "unnamed_multidimensional_array".
Definition at line 46 of file MultiDimensionalArray.tpp.
References std::vector< T >::data().
MultiDimensionalArray() [2/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (const std::string & name)
Constructor.
Parameters
name The name of the MultiDimensionalArray
Definition at line 57 of file MultiDimensionalArray.tpp.
References std::vector< T >::data().
MultiDimensionalArray() [3/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (const std::string & name, const std::vector< index_type > & dimensions)
Constructor.
Parameters
name The name of the MultiDimensionalArray
dimensions The dimensions of the MultiDimensionalArray
MultiDimensionalArray() [4/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (const std::string & name, const std::vector< index_type > & dimensions, const_pointer inputVector)
Constructor.
Parameters
name The name of the MultiDimensionalArray
dimensions The dimensions of the MultiDimensionalArray
inputVector The raw pointer to the data stored in column-major order
MultiDimensionalArray() [5/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (const MultiDimensionalArray< T > & other)
Copy constructor.
Definition at line 109 of file MultiDimensionalArray.tpp.
MultiDimensionalArray() [6/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (MultiDimensionalArray< T > && other)
Move constructor.
Definition at line 115 of file MultiDimensionalArray.tpp.
References std::forward().
MultiDimensionalArray() [7/7]
template<typename T > matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray (const MatvarHandler & handler)
Constructor to share the data ownership of another variable.
Parameters
handler The MatvarHandler handler to the matvar_t which has to be shared.
Definition at line 121 of file MultiDimensionalArray.tpp.
References std::vector< T >::data(), matioCpp::MatvarHandler::get(), matioCpp::Variable::initializeVariable(), matioCpp::MultiDimensionalArray, matioCpp::MatvarHandler::valueType(), and matioCpp::MatvarHandler::variableType().
~MultiDimensionalArray()
template<typename T > matioCpp::MultiDimensionalArray< T >::~MultiDimensionalArray
Destructor.
Definition at line 137 of file MultiDimensionalArray.tpp.
Member Function Documentation
clear()
template<typename T > void matioCpp::MultiDimensionalArray< T >::clear
Clear the multidimensional array.
Definition at line 269 of file MultiDimensionalArray.tpp.
References std::move().
data() [1/2]
template<typename T > matioCpp::MultiDimensionalArray< T >::pointer matioCpp::MultiDimensionalArray< T >::data
Direct access to the underlying array.
Note
The underlying array is in column-major format.
Returns
A pointer to the internal data.
Definition at line 275 of file MultiDimensionalArray.tpp.
data() [2/2]
template<typename T > matioCpp::MultiDimensionalArray< T >::const_pointer matioCpp::MultiDimensionalArray< T >::data
Direct access to the underlying array.
Note
The underlying array is in column-major format.
Returns
A pointer to the internal data.
Definition at line 281 of file MultiDimensionalArray.tpp.
fromVectorizedArray()
template<typename T > bool matioCpp::MultiDimensionalArray< T >::fromVectorizedArray (const std::vector< index_type > & dimensions, const_pointer inputVector)
Set from a vectorized array.
Note
The pointer is supposed to be in column-major format.
Parameters
dimensions The input dimensions
inputVector The input pointer.
Returns
True if successful.
Definition at line 157 of file MultiDimensionalArray.tpp.
References std::endl(), and matioCpp::MultiDimensionalArray.
indicesFromRawIndex()
template<typename T > bool matioCpp::MultiDimensionalArray< T >::indicesFromRawIndex (size_t rawIndex, std::vector< index_type > & el) const
Get the indices given the raw index.
Parameters
rawIndex The input raw index from which to compute the indices
el The output indices
Returns
True if successful, false otherwise (for example if rawIndex is out of bounds)
Definition at line 195 of file MultiDimensionalArray.tpp.
References std::endl().
numberOfElements()
template<typename T > matioCpp::MultiDimensionalArray< T >::index_type matioCpp::MultiDimensionalArray< T >::numberOfElements
Get the total number of elements in the array.
Returns
The total number of elements
Definition at line 287 of file MultiDimensionalArray.tpp.
operator()() [1/4]
template<typename T > reference matioCpp::MultiDimensionalArray< T >::operator() (const std::vector< index_type > & el)
Access specified element.
Parameters
el The element to be accessed.
Warning
Each element of el has to be strictly smaller than the corresponding dimension.
Returns
A reference to the element.
operator()() [2/4]
template<typename T > value_type matioCpp::MultiDimensionalArray< T >::operator() (const std::vector< index_type > & el) const
Access specified element.
Parameters
el The element to be accessed.
Warning
Each element of el has to be strictly smaller than the corresponding dimension.
Returns
A copy to the element.
operator()() [3/4]
template<typename T > reference matioCpp::MultiDimensionalArray< T >::operator() (index_type el)
Access specified element.
Parameters
el The element to be accessed (raw index).
Returns
A reference to the element.
operator()() [4/4]
template<typename T > value_type matioCpp::MultiDimensionalArray< T >::operator() (index_type el) const
Access specified element.
Parameters
el The element to be accessed (raw index).
Returns
A copy to the element.
operator=() [1/2]
template<typename T > matioCpp::MultiDimensionalArray< T > & matioCpp::MultiDimensionalArray< T >::operator= (const MultiDimensionalArray< T > & other)
Assignement operator (copy) from another MultiDimensionalArray.
Parameters
other The other MultiDimensionalArray.
Note
Also the name is copied
Returns
A reference to this MultiDimensionalArray.
Definition at line 143 of file MultiDimensionalArray.tpp.
operator=() [2/2]
template<typename T > matioCpp::MultiDimensionalArray< T > & matioCpp::MultiDimensionalArray< T >::operator= (matioCpp::MultiDimensionalArray< T > && other)
Assignement operator (move) from another MultiDimensionalArray.
Parameters
other The other MultiDimensionalArray.
Note
Also the name is copied
Returns
A reference to this MultiDimensionalArray.
Definition at line 150 of file MultiDimensionalArray.tpp.
References std::forward().
operator[]() [1/4]
template<typename T > reference matioCpp::MultiDimensionalArray< T >::operator[] (const std::vector< index_type > & el)
Access specified element.
Parameters
el The element to be accessed.
Warning
Each element of el has to be strictly smaller than the corresponding dimension.
Returns
A reference to the element.
operator[]() [2/4]
template<typename T > value_type matioCpp::MultiDimensionalArray< T >::operator[] (const std::vector< index_type > & el) const
Access specified element.
Parameters
el The element to be accessed.
Warning
Each element of el has to be strictly smaller than the corresponding dimension.
Returns
A copy to the element.
operator[]() [3/4]
template<typename T > reference matioCpp::MultiDimensionalArray< T >::operator[] (index_type el)
Access specified element.
Parameters
el The element to be accessed (raw index).
Returns
A reference to the element.
operator[]() [4/4]
template<typename T > value_type matioCpp::MultiDimensionalArray< T >::operator[] (index_type el) const
Access specified element.
Parameters
el The element to be accessed (raw index).
Returns
A copy to the element.
rawIndexFromIndices()
template<typename T > matioCpp::MultiDimensionalArray< T >::index_type matioCpp::MultiDimensionalArray< T >::rawIndexFromIndices (const std::vector< index_type > & el) const
Get the index in the vectorized array corresponding to the provided indices.
Parameters
el The desired element
Warning
It checks if the element is in the bounds only in debug mode.
Since the array is stored in column-major, an element (i,j,k,l,..) of an array of dimensions (n,m,p,k,...) corresponds to a row index equal to i + j*n + k*n*m + l*n*m*p +...
Returns
the index in the vectorized array corresponding to the provided indices
Definition at line 175 of file MultiDimensionalArray.tpp.
resize()
template<typename T > void matioCpp::MultiDimensionalArray< T >::resize (const std::vector< index_type > & newDimensions)
Resize the vector.
Parameters
newDimensions The new dimensions.
Warning
Previous data is lost.
Definition at line 246 of file MultiDimensionalArray.tpp.
References std::vector< T >::data(), std::endl(), and matioCpp::MultiDimensionalArray.
setName()
template<typename T > bool matioCpp::MultiDimensionalArray< T >::setName (const std::string & newName)
Change the name of the Variable.
Parameters
newName The new name
Returns
True if successful.
Definition at line 240 of file MultiDimensionalArray.tpp.
toSpan() [1/2]
template<typename T > matioCpp::Span< typename matioCpp::MultiDimensionalArray< T >::element_type > matioCpp::MultiDimensionalArray< T >::toSpan
Get this MultiDimensionalArray as a Span.
Definition at line 228 of file MultiDimensionalArray.tpp.
References matioCpp::make_span().
toSpan() [2/2]
template<typename T > const matioCpp::Span< const typename matioCpp::MultiDimensionalArray< T >::element_type > matioCpp::MultiDimensionalArray< T >::toSpan
Get this MultiDimensionalArray as a Span (const version)
Definition at line 234 of file MultiDimensionalArray.tpp.
References matioCpp::make_span().
The documentation for this class was generated from the following files:
include/matioCpp/ForwardDeclarations.h
include/matioCpp/MultiDimensionalArray.h
include/matioCpp/impl/MultiDimensionalArray.tpp