matio-cpp: matioCpp::details::extent_type< Ext > Class Template Reference
matioCpp::details::extent_type< Ext > Class Template Reference
#include <matioCpp/Span.h>
Public Types
using index_type = std::ptrdiff_t
Public Member Functions
MATIOCPP_CONSTEXPR extent_type () noexcept
template<index_type Other>
MATIOCPP_CONSTEXPR extent_type (extent_type< Other > ext)
MATIOCPP_CONSTEXPR extent_type (index_type size)
MATIOCPP_CONSTEXPR index_type size () const noexcept
Detailed Description
template<std::ptrdiff_t Ext>
class matioCpp::details::extent_type< Ext >
Definition at line 332 of file Span.h.
Member Typedef Documentation
index_type
template<std::ptrdiff_t Ext> using matioCpp::details::extent_type< Ext >::index_type = std::ptrdiff_t
Definition at line 335 of file Span.h.
Constructor & Destructor Documentation
extent_type() [1/3]
template<std::ptrdiff_t Ext> MATIOCPP_CONSTEXPR matioCpp::details::extent_type< Ext >::extent_type () inline noexcept
Definition at line 339 of file Span.h.
extent_type() [2/3]
template<std::ptrdiff_t Ext> template<index_type Other> MATIOCPP_CONSTEXPR matioCpp::details::extent_type< Ext >::extent_type (extent_type< Other > ext) inline
Definition at line 342 of file Span.h.
References matioCpp::dynamic_extent, and matioCpp::details::extent_type< Ext >::size().
extent_type() [3/3]
template<std::ptrdiff_t Ext> MATIOCPP_CONSTEXPR matioCpp::details::extent_type< Ext >::extent_type (index_type size) inline
Definition at line 349 of file Span.h.
References matioCpp::details::extent_type< Ext >::size().
Member Function Documentation
size()
template<std::ptrdiff_t Ext> MATIOCPP_CONSTEXPR index_type matioCpp::details::extent_type< Ext >::size () const inline noexcept
Definition at line 351 of file Span.h.
Referenced by matioCpp::details::extent_type< Ext >::extent_type(), and matioCpp::details::extent_type< dynamic_extent >::extent_type().
The documentation for this class was generated from the following file:
include/matioCpp/Span.h