matio-cpp: matioCpp::Variable Class Reference
matioCpp::Variable Class Reference
The matioCpp::Variable class is the equivalent of matvar_t in matio.
#include <matioCpp/Variable.h>
Public Member Functions
Variable ()
Default constructor.
Variable (const matvar_t *inputVar)
Constructor from an existing matvar_t pointer.
Variable (const Variable &other)
Copy constructor.
Variable (Variable &&other)
Move constructor.
Variable (const MatvarHandler &handler)
Constructor to share the data ownership of another variable.
~Variable ()
Destructor.
Variable & operator= (const Variable &other)
Copy assignement.
Variable & operator= (Variable &&other)
Move assignement.
bool fromMatio (const matvar_t *inputVar)
Set this variable from an existing matio variable.
bool fromOther (const Variable &other)
Set this variable from another variable.
bool fromOther (Variable &&other)
Set this variable from another variable.
const matvar_t * toMatio () const
Convert this Variable to a matio variable.
matvar_t * toMatio ()
Convert this Variable to a matio variable.
std::string name () const
Get the name of the Variable.
matioCpp::VariableType variableType () const
Get the VariableType.
matioCpp::ValueType valueType () const
Get the ValueType.
bool isComplex () const
Get if the variable is complex.
matioCpp::Span< const size_t > dimensions () const
Get the dimensions of this object.
bool isValid () const
Check if the variable is valid.
matioCpp::Variable operator[] (const std::string &el)
Access field with specific name.
const matioCpp::Variable operator[] (const std::string &el) const
Access field with specific name.
template<typename T >
matioCpp::Element< T > asElement ()
Cast the variable as a Element.
template<typename T >
const matioCpp::Element< T > asElement () const
Cast the variable as a const Element.
template<typename T >
matioCpp::Vector< T > asVector ()
Cast the variable as a Vector.
template<typename T >
const matioCpp::Vector< T > asVector () const
Cast the variable as a const Vector.
matioCpp::String asString ()
Cast the variable as a String.
const matioCpp::String asString () const
Cast the variable as a const String.
matioCpp::String16 asString16 ()
Cast the variable as a String16.
const matioCpp::String16 asString16 () const
Cast the variable as a const String16.
matioCpp::String32 asString32 ()
Cast the variable as a String32.
const matioCpp::String32 asString32 () const
Cast the variable as a const String32.
template<typename T >
matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray ()
Cast the variable as a MultiDimensionalArray.
template<typename T >
const matioCpp::MultiDimensionalArray< T > asMultiDimensionalArray () const
Cast the variable as a const MultiDimensionalArray.
matioCpp::CellArray asCellArray ()
Cast the variable as a CellArray.
const matioCpp::CellArray asCellArray () const
Cast the variable as a const CellArray.
matioCpp::Struct asStruct ()
Cast the variable as a Struct.
const matioCpp::Struct asStruct () const
Cast the variable as a const Struct.
matioCpp::StructArray asStructArray ()
Cast the variable as a StructArray.
const matioCpp::StructArray asStructArray () const
Cast the variable as a const StructArray.
Protected Member Functions
bool initializeVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *data)
Initialize the variable.
bool initializeComplexVariable (const std::string &name, const VariableType &variableType, const ValueType &valueType, matioCpp::Span< const size_t > dimensions, void *realData, void *imaginaryData)
Initialize a complex variable.
template<typename T >
bool initializeComplexVector (const std::string &name, const Span< T > realInputVector, const Span< T > imaginaryInputVector)
Initialize a complex vector.
bool changeName (const std::string &newName)
Change the name of the variable.
size_t getArrayNumberOfElements () const
Get the total number of elements in the array.
bool setCellElement (size_t linearIndex, const Variable &newValue)
Set a cell element at a specified linear position.
Variable getCellElement (size_t linearIndex)
Get a cell element at a specified linear position.
const Variable getCellElement (size_t linearIndex) const
Get a cell element at a specified linear position.
size_t getStructNumberOfFields () const
Get the total number of fields in the variable, considered as a struct.
char *const * getStructFields () const
Get the list of fields in the variable, considered as a struct.
bool getStructFieldIndex (const std::string &field, size_t &index) const
Get the index of the specified field in the variable, considered as a struct.
bool setStructField (size_t index, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct at the specified position.
bool addStructField (const std::string &newField)
Add a new field to the variable, considered as a struct.
bool setStructField (const std::string &field, const Variable &newValue, size_t structPositionInArray=0)
Set the field of the struct given the newValue name.
Variable getStructField (size_t index, size_t structPositionInArray=0)
Get the specified field in the variable, considered as a struct.
const Variable getStructField (size_t index, size_t structPositionInArray=0) const
Get the specified field in the variable, considered as a struct.
Struct getStructArrayElement (size_t linearIndex)
Get an element of the variable, considered as a StructArray.
const Struct getStructArrayElement (size_t linearIndex) const
Get an element of the variable, considered as a StructArray.
virtual bool checkCompatibility (const matvar_t *inputPtr, matioCpp::VariableType variableType, matioCpp::ValueType valueType) const
Check if an input matio pointer is compatible with the specified variable.
Detailed Description
The matioCpp::Variable class is the equivalent of matvar_t in matio.
It is supposed to be a basic access to object that are or need to be saved in a mat file.
Definition at line 22 of file Variable.h.
Constructor & Destructor Documentation
Variable() [1/5]
matioCpp::Variable::Variable ()
Default constructor.
Definition at line 379 of file Variable.cpp.
Variable() [2/5]
matioCpp::Variable::Variable (const matvar_t * inputVar)
Constructor from an existing matvar_t pointer.
Parameters
inputVar The input pointer. It has to be not null.
Definition at line 385 of file Variable.cpp.
References matioCpp::MatvarHandler::duplicateMatvar().
Variable() [3/5]
matioCpp::Variable::Variable (const Variable & other)
Copy constructor.
Definition at line 391 of file Variable.cpp.
References matioCpp::MatvarHandler::duplicateMatvar(), isValid(), and toMatio().
Variable() [4/5]
matioCpp::Variable::Variable (matioCpp::Variable && other)
Move constructor.
Definition at line 400 of file Variable.cpp.
Variable() [5/5]
matioCpp::Variable::Variable (const MatvarHandler & handler)
Constructor to share the data ownership of another variable.
Parameters
handler The MatvarHandler handler to the matvar_t which has to be shared.
Definition at line 406 of file Variable.cpp.
~Variable()
matioCpp::Variable::~Variable ()
Destructor.
Definition at line 412 of file Variable.cpp.
Member Function Documentation
addStructField()
bool matioCpp::Variable::addStructField (const std::string & newField) protected
Add a new field to the variable, considered as a struct.
Parameters
newField The new field
Returns
True on success, false otherwise, for example if the struct is part of an array
Definition at line 285 of file Variable.cpp.
References std::string::c_str(), and std::endl().
asCellArray() [1/2]
matioCpp::CellArray matioCpp::Variable::asCellArray ()
Cast the variable as a CellArray.
Definition at line 587 of file Variable.cpp.
asCellArray() [2/2]
const matioCpp::CellArray matioCpp::Variable::asCellArray () const
Cast the variable as a const CellArray.
Definition at line 592 of file Variable.cpp.
asElement() [1/2]
template<typename T > matioCpp::Element< T > matioCpp::Variable::asElement
Cast the variable as a Element.
The implementation is in Element.tpp
Definition at line 176 of file Element.tpp.
asElement() [2/2]
template<typename T > const matioCpp::Element< T > matioCpp::Variable::asElement
Cast the variable as a const Element.
The implementation is in Element.tpp
Definition at line 182 of file Element.tpp.
asMultiDimensionalArray() [1/2]
template<typename T > matioCpp::MultiDimensionalArray< T > matioCpp::Variable::asMultiDimensionalArray
Cast the variable as a MultiDimensionalArray.
The implementation is in MultiDimensionalArray.tpp
Definition at line 345 of file MultiDimensionalArray.tpp.
asMultiDimensionalArray() [2/2]
template<typename T > const matioCpp::MultiDimensionalArray< T > matioCpp::Variable::asMultiDimensionalArray
Cast the variable as a const MultiDimensionalArray.
The implementation is in MultiDimensionalArray.tpp
Definition at line 351 of file MultiDimensionalArray.tpp.
asString() [1/2]
matioCpp::String matioCpp::Variable::asString ()
Cast the variable as a String.
Definition at line 617 of file Variable.cpp.
asString() [2/2]
const matioCpp::String matioCpp::Variable::asString () const
Cast the variable as a const String.
Definition at line 622 of file Variable.cpp.
asString16() [1/2]
matioCpp::String16 matioCpp::Variable::asString16 ()
Cast the variable as a String16.
Definition at line 627 of file Variable.cpp.
asString16() [2/2]
const matioCpp::String16 matioCpp::Variable::asString16 () const
Cast the variable as a const String16.
Definition at line 632 of file Variable.cpp.
asString32() [1/2]
matioCpp::String32 matioCpp::Variable::asString32 ()
Cast the variable as a String32.
Definition at line 637 of file Variable.cpp.
asString32() [2/2]
const matioCpp::String32 matioCpp::Variable::asString32 () const
Cast the variable as a const String32.
Definition at line 642 of file Variable.cpp.
asStruct() [1/2]
matioCpp::Struct matioCpp::Variable::asStruct ()
Cast the variable as a Struct.
Definition at line 597 of file Variable.cpp.
asStruct() [2/2]
const matioCpp::Struct matioCpp::Variable::asStruct () const
Cast the variable as a const Struct.
Definition at line 602 of file Variable.cpp.
asStructArray() [1/2]
matioCpp::StructArray matioCpp::Variable::asStructArray ()
Cast the variable as a StructArray.
Definition at line 607 of file Variable.cpp.
asStructArray() [2/2]
const matioCpp::StructArray matioCpp::Variable::asStructArray () const
Cast the variable as a const StructArray.
Definition at line 612 of file Variable.cpp.
asVector() [1/2]
template<typename T > matioCpp::Vector< T > matioCpp::Variable::asVector
Cast the variable as a Vector.
The implementation is in Vector.tpp
Definition at line 404 of file Vector.tpp.
asVector() [2/2]
template<typename T > const matioCpp::Vector< T > matioCpp::Variable::asVector
Cast the variable as a const Vector.
The implementation is in Vector.tpp
Definition at line 410 of file Vector.tpp.
changeName()
bool matioCpp::Variable::changeName (const std::string & newName) protected
Change the name of the variable.
Parameters
newName The new name to set
Returns
True if successful, false otherwise.
Definition at line 150 of file Variable.cpp.
References std::string::c_str().
checkCompatibility()
bool matioCpp::Variable::checkCompatibility (const matvar_t * inputPtr, matioCpp::VariableType variableType, matioCpp::ValueType valueType) const protected virtual
Check if an input matio pointer is compatible with the specified variable.
Parameters
inputPtr The input matvar_t pointer.
variableType The type of variable.
valueType The value type.
Returns
True if compatible. False otherwise, throwing errors.
Definition at line 374 of file Variable.cpp.
dimensions()
matioCpp::Span< const size_t > matioCpp::Variable::dimensions () const
Get the dimensions of this object.
Returns
The dimensions of the object
Definition at line 532 of file Variable.cpp.
References matioCpp::make_span().
Referenced by initializeVariable(), and matioCpp::File::write().
fromMatio()
bool matioCpp::Variable::fromMatio (const matvar_t * inputVar)
Set this variable from an existing matio variable.
Parameters
inputVar The not null pointer to a matio variable. The variable is cloned.
Returns
True if the cloning was successful.
Definition at line 437 of file Variable.cpp.
References std::endl(), matioCpp::get_types_from_matvart(), matioCpp::Unsupported, and matioCpp::UNSUPPORTED.
fromOther() [1/2]
bool matioCpp::Variable::fromOther (const Variable & other)
Set this variable from another variable.
Note
Child classes need to override this method to make sure that only compatible classes can be copied.
Parameters
other The Variable from which to copy the content (data, name, type, dimensions,..).
Returns
True if the cloning was successful.
Definition at line 457 of file Variable.cpp.
References toMatio().
fromOther() [2/2]
bool matioCpp::Variable::fromOther (matioCpp::Variable && other)
Set this variable from another variable.
Note
No copy is performed, but the original object is no more usable.
Child classes need to override this method to make sure that only compatible classes can be imported.
Parameters
other The source Variable. Content is moved.
Returns
True if the moving was successful.
Definition at line 462 of file Variable.cpp.
References std::endl().
getArrayNumberOfElements()
size_t matioCpp::Variable::getArrayNumberOfElements () const protected
Get the total number of elements in the array.
Returns
The total number of elements
Definition at line 169 of file Variable.cpp.
getCellElement() [1/2]
matioCpp::Variable matioCpp::Variable::getCellElement (size_t linearIndex) protected
Get a cell element at a specified linear position.
Parameters
linearIndex The linear index of the specified element
Returns
A Variable with a weak ownership to the underlying mat variable. This means that the data can be changed, but the variable cannot be resized and the name cannot change.
Definition at line 211 of file Variable.cpp.
getCellElement() [2/2]
const matioCpp::Variable matioCpp::Variable::getCellElement (size_t linearIndex) const protected
Get a cell element at a specified linear position.
Parameters
linearIndex The linear index of the specified element
Returns
A const Variable with a weak ownership to the underlying mat variable.
Definition at line 217 of file Variable.cpp.
getStructArrayElement() [1/2]
matioCpp::Struct matioCpp::Variable::getStructArrayElement (size_t linearIndex) protected
Get an element of the variable, considered as a StructArray.
Note
This allocates memory, one pointer per sruct field, but the pointers point to data in the array
Parameters
linearIndex The linear index of the struct to retrieve
Returns
A Struct with a weak ownership to the underlying mat variable. This means that the data can be changed, but the variable cannot be resized and the name cannot change.
Definition at line 342 of file Variable.cpp.
References std::string::c_str(), std::vector< T >::data(), matioCpp::Delete, and std::to_string().
getStructArrayElement() [2/2]
const matioCpp::Struct matioCpp::Variable::getStructArrayElement (size_t linearIndex) const protected
Get an element of the variable, considered as a StructArray.
Note
This allocates memory, one pointer per sruct field, but the pointers point to data in the array
Parameters
linearIndex The linear index of the struct to retrieve
Returns
A const Struct with a weak ownership to the underlying mat variable.
Definition at line 358 of file Variable.cpp.
References std::string::c_str(), std::vector< T >::data(), matioCpp::Delete, and std::to_string().
getStructField() [1/2]
matioCpp::Variable matioCpp::Variable::getStructField (size_t index, size_t structPositionInArray = 0) protected
Get the specified field in the variable, considered as a struct.
Parameters
index The index of the field
structPositionInArray The linear position of the struct to set in the struct array
Returns
A Variable with a weak ownership to the underlying mat variable. This means that the data can be changed, but the variable cannot be resized and the name cannot change.
Definition at line 330 of file Variable.cpp.
getStructField() [2/2]
const matioCpp::Variable matioCpp::Variable::getStructField (size_t index, size_t structPositionInArray = 0) const protected
Get the specified field in the variable, considered as a struct.
Parameters
index The index of the field
structPositionInArray The linear position of the struct to set in the struct array
Returns
A const Variable with a weak ownership to the underlying mat variable.
Definition at line 336 of file Variable.cpp.
getStructFieldIndex()
bool matioCpp::Variable::getStructFieldIndex (const std::string & field, size_t & index) const protected
Get the index of the specified field in the variable, considered as a struct.
Parameters
field The field to search
index The index of the field
Returns
True if successfull, false otherwise.
Definition at line 235 of file Variable.cpp.
References std::string::c_str().
getStructFields()
char *const * matioCpp::Variable::getStructFields () const protected
Get the list of fields in the variable, considered as a struct.
Returns
The list of fields.
Definition at line 229 of file Variable.cpp.
Referenced by matioCpp::StructArray::setElement().
getStructNumberOfFields()
size_t matioCpp::Variable::getStructNumberOfFields () const protected
Get the total number of fields in the variable, considered as a struct.
Returns
The total number of fields
Definition at line 223 of file Variable.cpp.
initializeComplexVariable()
bool matioCpp::Variable::initializeComplexVariable (const std::string & name, const VariableType & variableType, const ValueType & valueType, matioCpp::Span< const size_t > dimensions, void * realData, void * imaginaryData) protected
Initialize a complex variable.
Parameters
name The name of the variable.
variableType The type of variable
valueType The type of each element in the variable
dimensions Vector containing the variable dimensions. The size of this vector should be at least 2.
realData A void pointer to the (flattened) real data. Check the documentation of initializeVariable for understanding how to obtain/interpret this vector.
imaginaryData A void pointer to the (flattened) imaginary data. Check the documentation of initializeVariable for understanding how to obtain/interpret this vector.
Returns
true in case the variable was correctly initialized.
Definition at line 75 of file Variable.cpp.
References std::vector< T >::assign(), matioCpp::Span< ElementType, Extent >::begin(), std::string::c_str(), std::vector< T >::data(), matioCpp::MatvarHandler::DeleteMatvar(), std::string::empty(), matioCpp::Span< ElementType, Extent >::end(), std::endl(), matioCpp::get_matio_types(), matioCpp::LOGICAL, matioCpp::Span< ElementType, Extent >::size(), and std::vector< T >::size().
Referenced by initializeComplexVector().
initializeComplexVector()
template<typename T > bool matioCpp::Variable::initializeComplexVector (const std::string & name, const Span< T > realInputVector, const Span< T > imaginaryInputVector) inline protected
Initialize a complex vector.
Parameters
name The name of the variable.
realInputVector The real input vector.
imaginaryInputVector The imaginary input vector.
Returns
true in case the variable was correctly initialized.
Definition at line 65 of file Variable.h.
References matioCpp::Span< ElementType, Extent >::data(), std::string::empty(), std::endl(), initializeComplexVariable(), name(), matioCpp::Span< ElementType, Extent >::size(), and matioCpp::Vector.
initializeVariable()
bool matioCpp::Variable::initializeVariable (const std::string & name, const VariableType & variableType, const ValueType & valueType, matioCpp::Span< const size_t > dimensions, void * data) protected
Initialize the variable.
Note
Matlab stores data in column-major format (https://it.mathworks.com/help/coder/ug/what-are-column-major-and-row-major-representation-1.html). Hence, given a multi-dimensional array of size n x m x p, the element (i, j, k) (with zero indexing) is at position i + j*n + k*n*m
Parameters
name The name of the variable.
variableType The type of variable
valueType The type of each element in the variable
dimensions Vector containing the variable dimensions. The size of this vector should be at least 2.
data A void pointer to the (flattened) data.
Returns
true in case the variable was correctly initialized.
Definition at line 16 of file Variable.cpp.
References std::vector< T >::assign(), std::string::c_str(), std::vector< T >::data(), matioCpp::MatvarHandler::DeleteMatvar(), dimensions(), std::string::empty(), std::endl(), matioCpp::MatvarHandler::get(), matioCpp::get_matio_types(), matioCpp::MatvarHandler::importMatvar(), matioCpp::LOGICAL, name(), std::vector< T >::size(), valueType(), and variableType().
Referenced by matioCpp::CellArray::CellArray(), matioCpp::Element< T >::Element(), matioCpp::MultiDimensionalArray< T >::MultiDimensionalArray(), matioCpp::Struct::Struct(), and matioCpp::StructArray::StructArray().
isComplex()
bool matioCpp::Variable::isComplex () const
Get if the variable is complex.
Returns
True if complex.
Definition at line 520 of file Variable.cpp.
isValid()
bool matioCpp::Variable::isValid () const
Check if the variable is valid.
A Variable may not be valid if it does not point to any data, or the the dimensions().size() < 2.
Returns
true if valid.
Definition at line 546 of file Variable.cpp.
Referenced by matioCpp::File::Impl::isVariableValid(), matioCpp::File::read(), setCellElement(), matioCpp::CellArray::setElement(), matioCpp::StructArrayElement< isConst >::setField(), setStructField(), and Variable().
name()
std::string matioCpp::Variable::name () const
Get the name of the Variable.
Returns
The name of the variable.
Definition at line 498 of file Variable.cpp.
Referenced by initializeComplexVector(), initializeVariable(), matioCpp::File::Impl::isVariableValid(), matioCpp::Struct::setField(), and matioCpp::StructArrayElement< isConst >::setField().
operator=() [1/2]
matioCpp::Variable & matioCpp::Variable::operator= (const Variable & other)
Copy assignement.
Parameters
other The variable to be copied
Returns
A reference to the variable.
Note
It calls fromOther(), with an assertion on its output.
Definition at line 421 of file Variable.cpp.
References matioCpp::unused().
operator=() [2/2]
matioCpp::Variable & matioCpp::Variable::operator= (matioCpp::Variable && other)
Move assignement.
Parameters
other The variable to be moved
Returns
A reference to the variable.
Note
It calls fromOther(), with an assertion on its output.
Definition at line 429 of file Variable.cpp.
References matioCpp::unused().
operator[]() [1/2]
matioCpp::Variable matioCpp::Variable::operator[] (const std::string & el)
Access field with specific name.
Parameters
el The name of the field to be accessed.
Returns
A Variable with a weak ownership to the underlying mat variable. This means that the data can be changed, but the variable cannot be resized and the name cannot change.
Note
This works only if the variable is a struct.
If the field is not found, the output variable is not valid.
Definition at line 551 of file Variable.cpp.
References std::endl(), and matioCpp::Struct.
operator[]() [2/2]
const matioCpp::Variable matioCpp::Variable::operator[] (const std::string & el) const
Access field with specific name.
Parameters
el The name of the field to be accessed.
Warning
Each element of el has to be strictly smaller than the corresponding dimension.
Returns
A const Variable with a weak ownership to the underlying mat variable.
Note
This works only if the variable is a struct.
If the field is not found, the output variable is not valid.
Definition at line 569 of file Variable.cpp.
References std::endl(), and matioCpp::Struct.
setCellElement()
bool matioCpp::Variable::setCellElement (size_t linearIndex, const Variable & newValue) protected
Set a cell element at a specified linear position.
Parameters
linearIndex The linear index of the specified element
newValue The Variable that will be copied in the specified location
Returns
True if successful, false otherwise
Definition at line 180 of file Variable.cpp.
References matioCpp::MatvarHandler::DeleteMatvar(), std::endl(), matioCpp::MatvarHandler::GetMatvarDuplicate(), isValid(), and toMatio().
setStructField() [1/2]
bool matioCpp::Variable::setStructField (const std::string & field, const Variable & newValue, size_t structPositionInArray = 0) protected
Set the field of the struct given the newValue name.
Parameters
field The field to set
newValue The Variable that will be copied in the specified field
structPositionInArray The linear position of the struct to set in the struct array
Returns
True if successful, false otherwise (for example if the newValue is not valid)
Note
If the field is not found, a new field is created and appended to the struct, but only if the struct is not part of an array.
Definition at line 310 of file Variable.cpp.
References std::endl().
setStructField() [2/2]
bool matioCpp::Variable::setStructField (size_t index, const Variable & newValue, size_t structPositionInArray = 0) protected
Set the field of the struct at the specified position.
Parameters
index The linear index of the specified field
newValue The Variable that will be copied in the specified location
structPositionInArray The linear position of the struct to set in the struct array
Returns
True if successful, false otherwise (for example if the newValue is not valid)
Definition at line 257 of file Variable.cpp.
References matioCpp::MatvarHandler::DeleteMatvar(), std::endl(), matioCpp::MatvarHandler::GetMatvarDuplicate(), isValid(), and toMatio().
toMatio() [1/2]
matvar_t * matioCpp::Variable::toMatio ()
Convert this Variable to a matio variable.
Warning
Any modification to the matio variable is reflected to this Variable.
Returns
A matvar_t pointer.
Definition at line 491 of file Variable.cpp.
toMatio() [2/2]
const matvar_t * matioCpp::Variable::toMatio () const
Convert this Variable to a matio variable.
Warning
Any modification to the matio variable is reflected to this Variable.
Returns
A matvar_t pointer.
Definition at line 484 of file Variable.cpp.
Referenced by fromOther(), setCellElement(), setStructField(), Variable(), and matioCpp::File::write().
valueType()
matioCpp::ValueType matioCpp::Variable::valueType () const
Get the ValueType.
Returns
The ValueType
Definition at line 515 of file Variable.cpp.
Referenced by initializeVariable(), and matioCpp::File::write().
variableType()
matioCpp::VariableType matioCpp::Variable::variableType () const
Get the VariableType.
Returns
The VariableType
Definition at line 510 of file Variable.cpp.
Referenced by initializeVariable(), and matioCpp::File::write().
The documentation for this class was generated from the following files:
include/matioCpp/Variable.h
include/matioCpp/impl/Element.tpp
include/matioCpp/impl/MultiDimensionalArray.tpp
include/matioCpp/impl/Vector.tpp
src/Variable.cpp